# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "ghcr.io/nirev23"
  tag: "v1.0.2-75c9b0c"
  os: linux
  arch: amd64
secret:
  name: "tbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
